### ISSUE TITLE
add auto scaling for content server tasks

### ISSUE THREAD

**Issue by zxkane** [tuna/opentuna#19]
Content servers act as HTTP server for serving the file content. Each task container has maximum capability to process the data transferring. We can use auto scaling capability to increase the total throughput of content servers and cost optimization.

### Use Case

- [ ] add auto scaling for content server task
- [ ] unit tests

Based on the content server nature, the auto scaling should based on network traffic. Below are some criteria we should consider when designing the metrics for auto scaling, 

- fargate instance network capability
- efs client network throughput, currently maximum throughout is 500MB/s per client(https://docs.aws.amazon.com/efs/latest/ug/limits.html#limits-client-specific)

### Other

* [ ] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by jiegec** [comment]
How to get these metrics? It seems that there are only two builtin metrics: CPUUtilization and MemoryUtilization.

**Comment by zxkane** [comment]
Pls check [Amazon ECS Container Insights Metrics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics-ECS.html) that exposes `NetworkTxBytes` metrics.

**Comment by zxkane** [comment]
> Pls check [Amazon ECS Container Insights Metrics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics-ECS.html) that exposes `NetworkTxBytes` metrics.

Container insight is not available in China regions yet. 😞

**Comment by zxkane** [comment]
[Running CloudWatch agent as sidecar](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/deploy_servicelens_CloudWatch_agent_deploy_ECS.html) to collect network metrics might be a workaround for China regions.
