### ISSUE TITLE
Support separated domain name for pypi

### ISSUE THREAD

**Issue by zxkane** [tuna/opentuna#21]
Use separated domain name for pypi mirror, for example `pypi.xxx.com`.

### Use Case

Due to we are sharing the doc among tuna sites, we need a separated domain name for pypi repo.

### Proposed Solution

---

This is a :rocket: Feature Request

**Comment by jiegec** [comment]
Should it be served by CloudFront? like:

pypi.xxx.com -> elb.xxx.com/pypi

**Comment by zxkane** [comment]
> Should it be served by CloudFront? like:
> 
> pypi.xxx.com -> elb.xxx.com/pypi

Yes. Use same alb origin for it. We can create different server based on `host` name on content server.
