### ISSUE TITLE
create new boltdb for new tunasync manager

### ISSUE THREAD

**Issue by zxkane** [tuna/opentuna#37]
Sometimes the tunasync manager process is running(no any output in console), but the http server is not started yet. It's probably something wrong happened in tunasync.

Due to the tunasync manager is managed by ASG that has health checking for http service of manager, the unhealthy instance will be terminated then start new one. The manager works after restarting several times.

For our infra, we might do following things to help investigate it,

- enable log of tunasync manager
- collect logs via cloudwatch agent

Current conf of tunasync manager,

https://github.com/tuna/opentuna/blob/7e91fe259089ccabaa1c6bc764e7c962c32668dd/lib/tuna-manager-user-data.txt#L40-L51

### Proposed solution

Let's always create a new boltdb file for new instance of tunasync manager. We might follow below rules to create the boltdb file,

- create boltdb file with current timestamp and instance id
- use file regex pattern to search the existing boltdb files to copy the latest one as new one

**Comment by jiegec** [comment]
I have observed the same thing, and it disappears after removing the database manually. So I think this might be caused by database corruptiong

**Comment by zxkane** [comment]
Is it possible caused by the tunasync manager failing on using the shared database file?

**Comment by jiegec** [comment]
Yes.

**Comment by zxkane** [comment]
How about always creating new db file for new tunasync manager? Will the existing worker periodically report the sync status? If so, how long the worker will send status to manager?

**Comment by jiegec** [comment]
> How about always creating new db file for new tunasync manager?

I think it's ok, because manager should not exit too often.

> Will the existing worker periodically report the sync status? If so, how long the worker will send status to manager?

When job status changes (i.e. running, finished, failed), it will report the sync status. So the upper bound of time of missing repo status is the sync interval.

**Comment by jiegec** [comment]
> Is it possible caused by the tunasync manager failing on using the shared database file?

Found some relevant issues:

https://github.com/boltdb/bolt/issues/562
https://github.com/boltdb/bolt/issues/690

**Comment by jiegec** [comment]
Maybe we can move the db path out of NFS?

**Comment by zxkane** [comment]
> Maybe we can move the db path out of NFS?

It's fine for me. Could you provide other ways to sync the mirror tasks from running workers? The data lag is unacceptable if depending on the interval of sync task.

**Comment by jiegec** [comment]
> Could you provide other ways to sync the mirror tasks from running workers? The data lag is unacceptable if depending on the interval of sync task.

I have two possible solutions:

1. The manager gets a list of ip of workers, and ask them upon start
2. The workers report their status in a short interval

**Comment by zxkane** [comment]
> > Could you provide other ways to sync the mirror tasks from running workers? The data lag is unacceptable if depending on the interval of sync task.
> 
> I have two possible solutions:
> 
> 1. The manager gets a list of ip of workers, and ask them upon start
> 2. The workers report their status in a short interval

I would like to go with option 2. Option 1 might introduce the third party storage for IPs of worker and maintain the lifecycle of workers.

**Comment by zxkane** [comment]
Any progress for this one? We're running into this issue again when deploying latest changes.

**Comment by jiegec** [comment]
I got the following strace when tunasync manager stucks:

![image](https://user-images.githubusercontent.com/6127678/92255019-54cf4980-ef04-11ea-8663-21ccaf69a042.png)

It is stucked in `flock` syscall.

**Comment by jiegec** [comment]
I plan to add a separate db backend for this problem.

**Comment by zxkane** [comment]
> I plan to add a separate db backend for this problem.

sure thing. go ahead.
