### ISSUE TITLE
tunasync failed on rsync based on upstream due to 'cannot delete non-empty directory'

### ISSUE THREAD

**Issue by zxkane** [tuna/opentuna#38]
When syncing from rsync based upstream, the syncing fails on below errors,

```
03:59:05 cannot delete non-empty directory: pool/main/d/docker-swarm
03:59:10 cannot delete non-empty directory: pool/main/d/denyhosts
03:59:28 cannot delete non-empty directory: pool/main/f/filemanager-actions
03:59:35 cannot delete non-empty directory: pool/main/g/gversion-plugin
...
```

It's caused by the directories containing the non-empty tmp folder `.~tmp~`.

Is there something could be improved in upstream tool `tunasync` or we have to manually clean those tmp folders?

### Environment

  - **CDK CLI Version:** 
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**

### Other

--- 

This is :bug: Bug Report

**Comment by jiegec** [comment]
Maybe we can ask rsync to exclude these files.

**Comment by zxkane** [comment]
Current rsync cmd already excludes the folder,

`rsync -aHvh --no-o --no-g --stats --exclude .~tmp~/ --delete --delete-after --delay-updates --safe-links --timeout=120 rsync://mirrors.tuna.tsinghua.edu.cn/debian/ /data/debian`

I guess the tmp folder was introduced and left by previous partial syncing and the folder had been removed from tuna's mirror.

**Comment by zxkane** [comment]
resolved it via cleaning those tmp folders manually.
