### ISSUE TITLE
rsync error: Too many links (31)

### ISSUE THREAD

**Issue by zxkane** [tuna/opentuna#39]
Checking the log of debian, found few errors like below,

```
rsync: link "/mnt/efs/opentuna/data/debian/dists/buster/contrib/by-hash/SHA256/.f61f27bd17de546264aa58f40f3aafaac7021e0ef69c17f6b1b4cd7664a037ec.22970" => dists/buster-proposed-updates/contrib/by-hash/SHA256/f61f27bd17de546264aa58f40f3aafaac7021e0ef69c17f6b1b4cd7664a037ec failed: Too many links (31)
rsync: link "/mnt/efs/opentuna/data/debian/dists/buster/contrib/by-hash/SHA256/.f61f27bd17de546264aa58f40f3aafaac7021e0ef69c17f6b1b4cd7664a037ec.22970" => dists/buster/contrib/debian-installer/binary-all/by-hash/MD5Sum/4a4dd3598707603b3f76a2378a4504aa failed: Too many links (31)
```

I can manually create the same symbol link. Not sure why rsync reports it.

### Environment

  - **CDK CLI Version:** 
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**

### Other

--- 

This is :bug: Bug Report

**Comment by zxkane** [comment]
We are suffering the EFS limit `Maximum number of hard links to a file: 177.`. 

https://docs.aws.amazon.com/efs/latest/ug/limits.html#limits-fs-specific

**Comment by zxkane** [comment]
Is it possible to override default rsync option `-aHvh` to copy file content instead of creating hard link?

**Comment by jiegec** [comment]
Try '--no-H'?
