### ISSUE TITLE
automatically request/renew SSL cert from let's encrypt

### ISSUE THREAD

**Issue by zxkane** [tuna/opentuna#42]
Due to the limitation of CloudFront and ACM in China regions, we have to import SSL cert into IAM for CloudFront.

Use free cert from Let's encrypt as workaround.

### Proposed Solution

- [ ] Use EventBridge to time based trigger
- [ ] Use Lambda/EC2 to request/renew cert from Let's encrypt
- [ ] Use DNS challenge via R53
- [ ] Upload cert to IAM
- [ ] Put new cert id to SSM parameter store
- [ ] Fetch latest cert id from SSM parameter store for open tuna stack

### Other

* [ ] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by jiegec** [comment]
One example to follow:

https://www.paulcourt.co.uk/article/lets-encrypt-wildcard-route53

**Comment by jiegec** [comment]
The lambda function needs to:
1. use certbot to request certificate (with permissions to route53)
2. upload certificate to iam
3. put iam cert id to ssm paramter store
4. update CloudFormation stack

**Comment by zxkane** [comment]
A reference tool,

https://github.com/dlapiduz/certbot-s3front
