### ISSUE TITLE
allocate EIP and bind to instance of tunasync worker

### ISSUE THREAD

**Issue by zxkane** [tuna/opentuna#43]
We put tunasync worker in public subnet to save the cost of NAT gateway. The IP address will be changed after the worker instance restarts.

The rsync upstream(see #40) might require whiltelist the IPs of rsync client.

### Other

* [ ] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by jiegec** [comment]
Some possible solutions:

https://stackoverflow.com/questions/34849360/how-to-assign-eip-to-autoscaling-group-of-vpc-in-cloudformation-template
https://heed.io/2019/05/24/aws-autoscaling-and-the-automatic-assignment-of-elastic-ips/
https://medium.com/@lakshman301195/elastic-ip-in-an-auto-scaling-group-a43c3bc9e74

They associate an EIP from EIP pool when instance starts.

**Comment by zxkane** [comment]
> Some possible solutions:
> 
> https://stackoverflow.com/questions/34849360/how-to-assign-eip-to-autoscaling-group-of-vpc-in-cloudformation-template
> https://heed.io/2019/05/24/aws-autoscaling-and-the-automatic-assignment-of-elastic-ips/
> https://medium.com/@lakshman301195/elastic-ip-in-an-auto-scaling-group-a43c3bc9e74
> 
> They associate an EIP from EIP pool when instance starts.

Yes. We can allocate two EIPs for the worker with pre-defined tags. Then query and associate the free EIP in ec2 user data.

**Comment by zxkane** [comment]
We don't need it so far, close it.
