### ISSUE TITLE
web portal customization

### ISSUE THREAD

**Issue by zxkane** [tuna/opentuna#47]
Customize web portal.

### Use Case

* Words
* ICP# if provided
* Hide hardcode mirrors, such as `AUR`
* only keep `Mirrors` in nav bar
* News only for this site
* Hide Domains selection
* Hide Server status section

---

This is a :rocket: Feature Request

**Comment by zxkane** [comment]
Hardcode mirror `AUR` still is showing.

**Comment by zxkane** [comment]
It would be better if we can hide `服务器状态` in related links.

**Comment by jiegec** [comment]
> Hardcode mirror `AUR` still is showing.
> It would be better if we can hide `服务器状态` in related links.

These are solved in #46, but CloudFront has cached the old version.

**Comment by zxkane** [comment]
> > Hardcode mirror `AUR` still is showing.
> > It would be better if we can hide `服务器状态` in related links.
> 
> These are solved in #46, but CloudFront has cached the old version. The ALB host has the newest one.

After invalidating the js cache, it works.
