### ISSUE TITLE
can not rebuild web portal image only if the opentuna-site is changed

### ISSUE THREAD

**Issue by zxkane** [tuna/opentuna#62]
After we submitted [new news of site](https://github.com/tuna/opentuna-site/pull/1), but we can not deploy the stack to pick up the latest content of opentuna-site.

### Reproduction Steps

see above

Because CDK calculates the image hash based on the content of the folder of `Dockerfile`. There is nothing change in CDK's perspective.

https://github.com/tuna/opentuna/blob/a6adf4d91d416ef9fbc18b155a530c8972d58470/web-portal/Dockerfile#L9

We should explicitly refer to the commit in opentuna-site.

### Environment

  - **CDK CLI Version:** 
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**

### Other

--- 

This is :bug: Bug Report

**Comment by zxkane** [comment]
Also it will a problem we can not rebuild the image if the content of opentuna-site is not changed. But Jekyll has different outputs based on the publication date of posts.

**Comment by jiegec** [comment]
Proposed solution: Track opentuna-site as submodule

**Comment by zxkane** [comment]
> Proposed solution: Track opentuna-site as submodule

Good idea. Let's go ahead to fix it.
